name: 'demo'
version: '3.5'

services:
  nest-app:
    build:
      context: .
      target: ${NODE_ENV}
      dockerfile: Dockerfile
    image: nest-app-${NODE_ENV}
    restart: unless-stopped
    env_file: 'env/.env.${NODE_ENV}'
    expose:
      - 3000
    ports:
      - '${LOCAL_APP_PORT}:3000'
    depends_on:
      - pg
  pg:
    extends:
      file: compose-pg.yaml
      service: pg
  pg-admin:
    extends:
      file: compose-pg.yaml
      service: pg-admin
