version: '3.5'

services:
  pg:
    image: postgres
    container_name: demo-db-pg-${NODE_ENV}
    restart: always
    env_file: 'env/.env.${NODE_ENV}'
    expose:
      - 5432
    ports:
      - '${LOCAL_PG_PORT}:5432'
  pg-admin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin-${NODE_ENV}
    restart: always
    env_file: 'env/.env.${NODE_ENV}'
    expose:
      - 80
    ports:
      - '${LOCAL_PGADMIN_PORT}:80'
