name: Github CD action

on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Deploy built file to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_NODE_HOST}}
          username: ${{secrets.SERVER_NODE_USER}}
          key: ${{secrets.SERVER_NODE_PRIVATE_KEY}}
          script: |
            cd $HOME/demo_api
            git pull
            bash ./scripts/rolling-update.sh
