on: # trigger workflow
  pull_request:
    types: [opened, reopened, edited]

jobs:
  setup:
    name: CI check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Format code
        run: pnpm format
      - name: Lint code
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build code
        run: pnpm build
      - name: Upload artifact to github runner
        uses: actions/upload-artifact@v3
        with:
          name: build-file
          path: |
            ./dist
            ./package.json
            ./pnpm-lock.yaml
            !**/dist/test/*
          retention-days: 3
