name: Update database

on:
  workflow_run:
    workflows: [Deploy built file to remote server]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy built file to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_NODE_HOST}}
          username: ${{secrets.SERVER_NODE_USER}}
          key: ${{secrets.SERVER_NODE_PRIVATE_KEY}}
          script: |
            cd $HOME/demo_api
            git pull
            bash ./scripts/run-migrations.sh
